### ISSUE TITLE
Client stops receiving flag updates after about 5 minutes

### ISSUE THREAD

**Issue by jdegges** [launchdarkly/cpp-sdks#243]
**Describe the bug**
  After about 5 minutes the launch darkly client will stop receiving flag updates through any registered listeners using `client.FlagNotifier().OnFlagChange()` as well as through a variation query like `client.BoolVariation(FEATURE_FLAG_KEY, false)`.
  
  **To reproduce**
* Checkout the repository, commit 6876f69e1d47f9d39e6a2110b7af66f69e32923f
* Modify the hello-c-client or hello-cpp-client examples to continuously query flag values by applying a diff like:
```
@@ -59,11 +60,14 @@ int main() {
         return 1;
     }
 
+    while (true) {
     bool flag_value =
         LDClientSDK_BoolVariation(client, FEATURE_FLAG_KEY, false);
 
     printf("*** Feature flag '%s' is %s for this user\n\n", FEATURE_FLAG_KEY,
            flag_value ? "true" : "false");
+    sleep(60);
+    }
```
* Build and run as usual: `mkdir build && cd build && cmake .. && make -j && ./examples/hello-c-client/hello-c` (or `./examples/hello-cpp-client/hello-cpp`)
* Toggle the flag value via the web ui about once every minute and observe the value change on the console
* After about 5 minutes the console will stop reflecting the most current flag value
  
**Expected behavior**
* The launch darkly client is capable of remaining connected and receiving the latest flag values.
* When the launch darkly client becomes disconnected or is otherwise unable to obtain latest flag values it notifies the caller of the situation so it can know what is happening and potentially take action.

**Logs**
Can provide logs upon request
  
**SDK version**
Commit 6876f69e1d47f9d39e6a2110b7af66f69e32923f
  
**Language version, developer tools**
Apple clang version 12.0.0 (clang-1200.0.32.29)
gcc v8
  
**OS/platform**
MacOS 13.4
Linux
  
**Additional context**
This behavior was reproduced using both the C++ and C interfaces of this cpp-sdks project on both MacOS and Linux using both the variation query interface, the all flags interface, and the OnFlagChange listener interface. In all attempts the client stopped working after about 5 minutes.

When the examples were instrumented with a `OnDataSourceStatusChange()` listener the listener callback was never executed.

When periodic polling of `client.Initialized()` was added to the examples it always returned "1".

A similar example application built using the latest version of github.com/launchdarkly/c-client-sdk (commit 78f663ae37093f7ec107e1ed5fa4e1eca175c63a) works just fine on MacOS 13.4. It remains connected and is able to receive the latest flag value without problem for long periods of time (>40 minutes).

**Comment by cwaldren-ld** [comment]
Hi @jdegges, thanks for bringing this to our attention. I'll investigate and get back to you.

**Comment by cwaldren-ld** [comment]
We have an erroneous 5 minute read timeout set on the server-sent-events connection. I'll prepare a bugfix shortly.
