### ISSUE TITLE
Respect the provided CMAKE_MSVC_RUNTIME_LIBRARY

### ISSUE THREAD

**Issue by magnushakansson** [launchdarkly/cpp-sdks#369]
**Is this a support request?**
No

**Describe the bug**
I think the assumption to set MSVC_RUNTIME_LIBRARY to dynamically-linked runtime library as done in
https://github.com/launchdarkly/cpp-sdks/pull/103/files#diff-fa09bb86eb7d88efd503b5dfecfeae4e7951e35abdb57860736023a3c75c6eb7R54 is not correct.

For various reasons we need to link our application with the statically linked library.

**To reproduce**
Link with an application built with statically linked runtime library.

**Expected behavior**
The SDK code should be possible to build with both dynamically linked and statically linked runtime library as decided by the consumer. So basically allow the provided CMAKE_MSVC_RUNTIME_LIBRARY to control the behavior (and you can fallback to the current config if it's not specified)

**Logs**
N/A

**SDK version**
launchdarkly-cpp-server-v3.3.0

**Language version, developer tools**
C++ 17 

**OS/platform**
Windows

**Additional context**
None

**Comment by cwaldren-ld** [comment]
Hi @magnushakansson , I think this makes sense - it should be the application developer's decision. I'll work on getting the CMake config updated. 

_Filed internally as 233262._

**Comment by cwaldren-ld** [comment]
Hi @magnushakansson , would you mind checking out https://github.com/launchdarkly/cpp-sdks/pull/370 and testing that it satisfies your requirements?

**Comment by magnushakansson** [comment]
> Hi @magnushakansson , would you mind checking out the #370 branch and testing that it satisfies your requirements?

Yes, it works well. Thanks for prompt action.

**Comment by cwaldren-ld** [comment]
Hi @magnushakansson , this has been merged to `main`. Let us know if you have any other issues.
