### ISSUE TITLE
 "LDConfigSetSSLCertificateAuthority" and "LDConfigSetVerifyPeer" are not available from 3.0.

### ISSUE THREAD

**Issue by ngangomsamananda** [launchdarkly/cpp-sdks#385]
**Is your feature request related to a problem? Please describe.**
 We are updating client sdk from v2.5.2 to v3.4.0 (c binding) but the equivalent replacement of `LDConfigSetSSLCertificateAuthority` and `LDConfigSetVerifyPeer` are not available. 

- **LDConfigSetSSLCertificateAuthority:** Set the path to the SSL certificate bundle used for peer authentication.
- **LDConfigSetVerifyPeer :** Set whether to verify the authenticity of the peer's certificate on network requests.

  
  **Describe the solution you'd like**
  Please provide the replacement for `LDConfigSetSSLCertificateAuthority` and `LDConfigSetVerifyPeer`.
  
  **Describe alternatives you've considered**
  
  **Additional context**
  Add any other context about the feature request here.

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda, you are correct, these are not available in the SDK at the moment.

I have filed an internal feature request.

_Filed internally as 238927_.

**Comment by ngangomsamananda** [comment]
@cwaldren-ld Thank you. 
How long does it take a feature request to complete? Will it be available in the next SDK release?

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda , I cannot provide an estimate, but I will address it as soon as I am able.

**Comment by ngangomsamananda** [comment]
Hi @cwaldren-ld, is there any particular reason why `LDConfigSetSSLCertificateAuthority` and `LDConfigSetVerifyPeer` are not included in v3.x? 
Could you please take up this issue on priority than the other tickets (https://github.com/launchdarkly/cpp-sdks/issues/392 and https://github.com/launchdarkly/cpp-sdks/issues/394) which I had requested?  We are not able to complete the sdk update because of these APIs.

**Comment by cwaldren-ld** [comment]
Hi, please accept my apologies for slow response as I am out of the office.

I will prioritize this feature when I return next week.

**Comment by ngangomsamananda** [comment]
@cwaldren-ld No worries. In one of the tickets, you had mentioned you will be out of office this week. I have added the comment so that you can have a look when you come back.

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda , the reason these APIs were not included was because we didn't have a proven use-case for them. 

Since you have requested them, I have begun work here: https://github.com/launchdarkly/cpp-sdks/pull/391

I will update you when the work is complete.

**Comment by ngangomsamananda** [comment]
@cwaldren-ld Thank you so much.

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda , I apologize this is taking longer than expected. I am still working on it. 

The `LDConfigSetVerifyPeer` will be released first, then `LDConfigSetSSLCertificateAuthority` will come after.

**Comment by ngangomsamananda** [comment]
@cwaldren-ld Let me know when `LDConfigSetVerifyPeer` is release. I appreciate you for working this on priority.

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda , we have released [C++ Client v3.5.0](https://github.com/launchdarkly/cpp-sdks/releases/tag/launchdarkly-cpp-client-v3.5.0) with support for disabling Peer Verification in TLS handshake.

Here is a [link](https://launchdarkly.github.io/cpp-sdks/libs/client-sdk/docs/html/client-sdk_2include_2launchdarkly_2client__side_2bindings_2c_2config_2builder_8h.html#af07656ee96842503823095fd6aa7d0e7) to the docs.

Example:
```c++
// First, create a new TLS Config builder
LDClientHttpPropertiesTlsBuilder tls_builder = LDClientHttpPropertiesTlsBuilder_New();

// Disable peer verification 
LDClientHttpPropertiesTlsBuilder_SkipVerifyPeer(tls_builder, true);

// Assuming you have an existing LDClientConfigBuilder
LDClientConfigBuilder_HttpProperties_Tls(config, tls_builder);
```

Please note, the SDK will emit logs informing you that TLS peer verification is disabled, since it can be considered a security flaw in many scenarios.

**Comment by ngangomsamananda** [comment]
@cwaldren-ld Thank you so much. I will check and let you know. 
One thing: is `LDClientHttpPropertiesTlsBuilder_Free()` need to be call? I saw this in the docs you have shared.

**Comment by cwaldren-ld** [comment]
Not normally. 

If you pass the builder into the ConfigBuilder, there is **no need** to call `LDClientHttpPropertiesTlsBuilder_Free()` (since the ConfigBuilder takes ownership of it.)

If you do not pass it into the ConfigBuilder, then **yes** you need to call `LDClientHttpPropertiesTlsBuilder_Free()`.

**Comment by ngangomsamananda** [comment]
Hi @cwaldren-ld , till now the replacement for `LDConfigSetVerifyPeer ` appears to be working fine. If I face any issue, I will reach out to you. Thanks

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda , please check out https://github.com/launchdarkly/cpp-sdks/pull/409 branch (`cw/sc-244781/custom-ca`) when you have a chance and test the new API:

```c
// First, create a new TLS Config builder
LDClientHttpPropertiesTlsBuilder tls_builder = LDClientHttpPropertiesTlsBuilder_New();

// Set path to a custom CA file
LDClientHttpPropertiesTlsBuilder_CustomCAFile(tls_builder, "path/to/your/custom_ca.pem");

// Assuming you have an existing LDClientConfigBuilder
LDClientConfigBuilder_HttpProperties_Tls(config, tls_builder);
```

**Comment by ngangomsamananda** [comment]
@cwaldren-ld I will do the testing when it is release. Thanks for working on that API.

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda , release is available here: https://github.com/launchdarkly/cpp-sdks/releases/tag/launchdarkly-cpp-client-v3.6.0

**Comment by ngangomsamananda** [comment]
Hi @cwaldren-ld, thank you so much for providing the new API's in short time.

**Comment by ngangomsamananda** [comment]
Hi @cwaldren-ld We are getting some repeated logs like for every 30 seconds. Do you know what are these logs for? If it's not a major issue,  is there a way to disable it?
![image](https://github.com/launchdarkly/cpp-sdks/assets/134058205/fd1fcb1f-c7b7-4ef1-8ab2-3af96aabd7ae)

**Comment by cwaldren-ld** [comment]
Yes, please check your `LD_LOG_LEVEL` environment variable (or log level defined in code.) 

These are debug-level logs that show that events are being sent to LaunchDarkly (flush) and that flag updates are arriving from LaunchDarkly (read bytes). 

If you use info level or above, you should not see them.

**Comment by ngangomsamananda** [comment]
@cwaldren-ld Thanks for clearing the doubts.

**Comment by ngangomsamananda** [comment]
Hi @cwaldren-ld , In some of the Windows machine our application is crash due to `LDClientConfigBuilder_HttpProperties_Tls`. On my machine the crash is not happened.  I am trying to understand what is issue. The snippet code is below.

`#include <iostream >
#include <launchdarkly/client_side/bindings/c/sdk.h>
#include <launchdarkly/bindings/c/context_builder.h>
#include <launchdarkly/client_side/bindings/c/config/builder.h>
#include <launchdarkly/bindings/c/object_builder.h>
#include <launchdarkly/bindings/c/memory_routines.h>



LDClientConfigBuilder ConfigBuilder = nullptr;
LDClientSDK g_pLDClient = nullptr;
LDListenerConnection m_listenerConnection = nullptr;

static bool enabled(const LDLogLevel level, void* user_data)
{
    return true;
}

void globalLogger(const LDLogLevel level, const char* text, void* user_data)
{
}
void initLDCallback(LDDataSourceStatus status, void* userData)
{
    LDDataSourceStatus_State statusState = LDDataSourceStatus_GetState(status);
    if (statusState == LDDataSourceStatus_State::LD_DATASOURCESTATUS_STATE_INITIALIZING)
    {
        // log message
    }
    else if (statusState == LDDataSourceStatus_State::LD_DATASOURCESTATUS_STATE_VALID)
    {
    }
    else if (statusState == LDDataSourceStatus_State::LD_DATASOURCESTATUS_STATE_INTERRUPTED)
    { 
    }
    else if (statusState == LDDataSourceStatus_State::LD_DATASOURCESTATUS_STATE_OFFLINE)
    {  
    }
    else
    {
    }
}
bool getPeerVerify()
{
    false;
}


int main()
{
    const char* userid = "user-key";
    const char* mobile_key = "mob-abc-123";
	ConfigBuilder = LDClientConfigBuilder_New(mobile_key);

    bool bOffline = false;
    
    if (bOffline)
        LDClientConfigBuilder_Offline(ConfigBuilder, bOffline);

    // logging
    LDLogBackend backend;
    LDLogBackend_Init(&backend);
    backend.Write = globalLogger;
    backend.Enabled = enabled;
    LDLoggingCustomBuilder customLogging = LDLoggingCustomBuilder_New();
    LDLoggingCustomBuilder_Backend(customLogging, backend);
    LDClientConfigBuilder_Logging_Custom(ConfigBuilder, customLogging);


    LDClientConfigBuilder_Events_PrivateAttribute(ConfigBuilder, "hubId");

    LDClientConfig config;
    LDStatus status = LDClientConfigBuilder_Build(ConfigBuilder, &config);
    if (!LDStatus_Ok(status)) {
      std::cout<<"ldcsdk client config builder failed";
    }


    LDClientHttpPropertiesTlsBuilder tlsBuilder = LDClientHttpPropertiesTlsBuilder_New();
    if (tlsBuilder)
    {
        // Disable peer verification
        LDClientHttpPropertiesTlsBuilder_SkipVerifyPeer(tlsBuilder, true);
        bool verifyPeer = getPeerVerify();
        if(verifyPeer)
        {
            LDClientHttpPropertiesTlsBuilder_SkipVerifyPeer(tlsBuilder, false);
        }
        LDClientConfigBuilder_HttpProperties_Tls(ConfigBuilder, tlsBuilder);
    }

    LDContextBuilder context_builder = LDContextBuilder_New();
    LDContextBuilder_AddKind(context_builder, "user", userid);

    LDContextBuilder_Attributes_SetPrivate(context_builder, "user", "email", LDValue_NewString("abc@gmail.com"));

    LDContext context = LDContextBuilder_Build(context_builder);
    g_pLDClient = LDClientSDK_New(config, context);
    unsigned int maxwait = 10 * 1000; /* 10 seconds */

    LDDataSourceStatusListener listener;
    LDDataSourceStatusListener_Init(&listener);
    listener.StatusChanged = initLDCallback;
    m_listenerConnection = LDClientSDK_DataSourceStatus_OnStatusChange(g_pLDClient, listener);

    bool initialized_successfully;
    if (LDClientSDK_Start(g_pLDClient, maxwait, &initialized_successfully)) 
    {
        if (initialized_successfully) 
        {
            std::cout << "LaunchDarkly: client Initialization Succeded." << std::endl;
        }
        else 
        {
            std::cout<<"LaunchDarkly: client Initialization failed\n";
        }
    } 
    else {
            std::cout<<"LaunchDarkly: The client is still initializing.\n";
    }

    bool initialized = LDClientSDK_Initialized(g_pLDClient);

}`

I am not sure where am I doing wrong. Could you help me on this?

**Comment by cwaldren-ld** [comment]
Yes, I will test it out. 

Just to clarify, is this a typo?
```
bool getPeerVerify()
{
    false;
}
```
it should be:
```
bool getPeerVerify()
{
    return false;
}
```

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda , I have found another problem:

This block of configuration:
```


LDClientHttpPropertiesTlsBuilder tlsBuilder = LDClientHttpPropertiesTlsBuilder_New();
if (tlsBuilder)
{
    // Disable peer verification
    LDClientHttpPropertiesTlsBuilder_SkipVerifyPeer(tlsBuilder, true);
    bool verifyPeer = getPeerVerify();
    if(verifyPeer)
    {
        LDClientHttpPropertiesTlsBuilder_SkipVerifyPeer(tlsBuilder, false);
    }
    LDClientConfigBuilder_HttpProperties_Tls(ConfigBuilder, tlsBuilder);
}
```

Needs to be placed **before** you call `LDStatus status = LDClientConfigBuilder_Build(ConfigBuilder, &config);`.

Remember, once you have called `LDClientConfigBuilder_Build` it is **undefined behavior** to use any other method that operates on the `ConfigBuilder`.

**Comment by ngangomsamananda** [comment]
> Yes, I will test it out.
> 
> Just to clarify, is this a typo?
> 
> ```
> bool getPeerVerify()
> {
>     false;
> }
> ```
> 
> it should be:
> 
> ```
> bool getPeerVerify()
> {
>     return false;
> }
> ```

Yes, that is typo. My bad.

**Comment by ngangomsamananda** [comment]
> Hi @ngangomsamananda , I have found another problem:
> 
> This block of configuration:
> 
> ```c++
> LDClientHttpPropertiesTlsBuilder tlsBuilder = LDClientHttpPropertiesTlsBuilder_New();
> if (tlsBuilder)
> {
>     // Disable peer verification
>     LDClientHttpPropertiesTlsBuilder_SkipVerifyPeer(tlsBuilder, true);
>     bool verifyPeer = getPeerVerify();
>     if(verifyPeer)
>     {
>         LDClientHttpPropertiesTlsBuilder_SkipVerifyPeer(tlsBuilder, false);
>     }
>     LDClientConfigBuilder_HttpProperties_Tls(ConfigBuilder, tlsBuilder);
> }
> ```
> 
> Needs to be moved **before** you call `LDStatus status = LDClientConfigBuilder_Build(ConfigBuilder, &config);`.
> 
> Remember, once you have called `LDClientConfigBuilder_Build` it is **undefined behavior** to use any other method that operates on the `ConfigBuilder`. This is because once you call Build, the memory is **deleted automatically**.
> 
> The nature of undefined behavior in C++ is that it may crash, it may do nothing at all, or it may do anything at all.

@cwaldren-ld 
I think this would be the issue. I have one more query. I want to change the peer verification after sdk connected. Can I do something like the below code?

```
LDClientHttpPropertiesTlsBuilder tlsBuilder = LDClientHttpPropertiesTlsBuilder_New();
if (tlsBuilder)
{
    // Disable peer verification
    LDClientHttpPropertiesTlsBuilder_SkipVerifyPeer(tlsBuilder, true);
    bool verifyPeer = getPeerVerify();
    if(verifyPeer)
    {
        LDClientHttpPropertiesTlsBuilder_SkipVerifyPeer(tlsBuilder, false);
    }
    LDClientConfigBuilder_HttpProperties_Tls(ConfigBuilder, tlsBuilder);
}

LDClientConfig config;
LDStatus status = LDClientConfigBuilder_Build(ConfigBuilder, &config);
LDContext context = LDContextBuilder_Build(context_builder);
g_pLDClient = LDClientSDK_New(config, context);
unsigned int maxwait = 10 * 1000; /* 10 seconds */

if (LDClientSDK_Start(g_pLDClient, maxwait, &initialized_successfully)) 
{
}

// Enable peer verify
 LDClientHttpPropertiesTlsBuilder_SkipVerifyPeer(tlsBuilder, false);
```

**Comment by cwaldren-ld** [comment]
> I want to change the peer verification after sdk is connected. Can I do something like the below code?
No, that is not supported. The snippet you provide is also undefined behavior.

May I please ask what is the situation that would require changing the peer verification mode at runtime? The way the SDK is setup is that you configure it once, and then use it. 

If you need to change configuration, generally you should destroy the SDK and create a new one.

**Comment by ngangomsamananda** [comment]
@cwaldren-ld Thanks for clearing the doubts. 
In the old version of sdk the peer verification was change at runtime using ` LDConfigSetVerifyPeer`. I was replacing that. Seeing in the code it looks like changing the peer verification mode at runtime for some specific use case. This is handled by some other team. I will check with them if it's really necessary to change peer verification at runtime and what are the use cases.

**Comment by ngangomsamananda** [comment]
@cwaldren-ld We have another crash issue. This is on MacOS machines. Some of the people face the issue. But I could not reproduce it. I am still not sure when the crash got occurred and why. The only thing I know is the crash happened after the SDK is configured and running. I have is the crash log. I am not sure that is enough for you to identify the root cause of the crash. 
![Screenshot 2024-06-11 at 2 44 26 PM](https://github.com/launchdarkly/cpp-sdks/assets/134058205/018dcd92-94d5-4325-be26-12eedbe79180)
![image (3)](https://github.com/launchdarkly/cpp-sdks/assets/134058205/7082ee30-9358-4427-8cb8-c15fdaae3bdd)

On different thread this is showing:
![Screenshot 2024-06-12 at 1 00 38 PM](https://github.com/launchdarkly/cpp-sdks/assets/134058205/51a8d4d4-14ad-41c2-8af1-e742ae9089da)
 
I have edited code of https://github.com/launchdarkly/cpp-sdks/issues/385#issuecomment-2160120815 to get you better understanding of the scenario. In our case` resetNewUserContext` is call multiple times. 

FYI, the binaries which is use here is built by me by running the script https://github.com/launchdarkly/cpp-sdks/blob/main/scripts/build-release.sh because I needed the Universal Binaries and also boost needed to be statically link.

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda , it is not allowed to call Identify in two scenarios:
(1) while initialization is in progress
(2) while another Identify is taking place

Doing so could cause a crash. 

[See here](https://launchdarkly.github.io/cpp-sdks/libs/client-sdk/docs/html/sdk_8h.html#a7adc06d078a2f0ef249b09746addb19f):
> Only one Identify call can be in progress at once; calling it concurrently invokes undefined behavior.

If you need to call Identify after calling Start, make sure you do it only if Start operation completed. For example:
```c++
bool initialized_successfully;
if LDClientSDK_Start(client, 5000, &initialized_successfully)) {
    if (initialized_successfully) {
        // In this case you could call Identify.
    else {
        // Initialization failed, you should handle the error. 
    }
} else {
   // It is undefined behavior to call Identify in this case, because the Start operation is still in progress.
   // In other words, Start is taking longer than 5 seconds to complete and is still happening in the background.
}
```

Similarly with Identify:
```c++
bool identified_successfully;
if LDClient_Identify(client, context, 5000, &identified_successfully)) {
    if (identified_successfully) {
        // The identify succeeded, you could call Identify again in this case.
    else {
        // The identify failed, you should handle the error.
    }
} else {
    // It is undefined behavior to call Identify in this case, because the Identify operation is still in progress.
}
```

**Comment by cwaldren-ld** [comment]
To help you, I need to know if your application is structured as an event-driven architecture, or blocking architecture. 

In other words does your application do blocking I/O calls everywhere (wait for the result to complete), or does it use callbacks to know when operations are complete?

If blocking, you could call `LDClientSDK_Initialized()` repeatedly in a loop with a short wait time to know when the operation is complete. 

If callbacks, you could register a DataSourceStatus listener and receive a callback when the operation is complete.

**Comment by ngangomsamananda** [comment]
Hi @cwaldren-ld , we use the callback method. It's also present in the above code https://github.com/launchdarkly/cpp-sdks/issues/385#issuecomment-2160120815. 
 I have looked in the application logs today. It looks like the crash happened when internet connectivity gets restored. 
So, when the Internet connectivity is down, we get a log "read timeout reached" then I get a callback status `LDDataSourceStatus_State::LD_DATASOURCESTATUS_STATE_SHUTDOWN`.
Then when the internet connection is restored the `LDClient_Identify` get call. Perhaps before the sdk is connected back the `LDClient_Identify` is called cause the crash?

From the log I can see after the callback status `LDDataSourceStatus_State::LD_DATASOURCESTATUS_STATE_SHUTDOWN` there is `LDDataSourceStatus_State::LD_DATASOURCESTATUS_STATE_INITIALIZING` . `LDDataSourceStatus_State::LD_DATASOURCESTATUS_STATE_INITIALIZING` callbacks status whenever we call `LDClient_Identify` method.

**Comment by cwaldren-ld** [comment]
@ngangomsamananda , yes, it is likely the Identify call is interfering with the SDK automatically restoring the streaming connection when the internet is back. 

Please note: if the connection is lost, there is no need to call `Identify`. It only needs to be called if the Context attributes have changed (such as context key, kind, or any other attribute.)

I understand this makes it difficult to use Identify correctly. We are planning a way to ensure this is safer in future version of SDK.

**Comment by ngangomsamananda** [comment]
@cwaldren-ld  I think that was the issue. Identify call is interfering with the SDK automatically restoring the streaming. Now I have few conditions check before calling the Identify. I hope this resolve the issue.

**Comment by ngangomsamananda** [comment]
Hi @cwaldren-ld, we get another issue. we are not getting expected result from the old and the new implementation of `LDClientSDK_JsonVariation`. 

Old Sdk code:

`   std::string value = "[]";
   std::string flagName = "flag-name";
    struct LDJSON* fallback = LDJSONDeserialize(value.c_str() );
    struct LDJSON* evaluation = LDJSONVariation(g_pLDClient, flagName.c_str(), fallback);
    char* evaluationString = LDJSONSerialize(evaluation);
    flagValue = JSONNode(evaluationString);
    LDFree(evaluation);
    LDFree(fallback);`

In the new SDK the same code is replaced with:
`     std::string value = "[]";
       std::string flagName = "flag-name";
       LDValue defaultValue = LDValue_NewString(defaultFlagValue.c_str());
        LDValue resultValue = LDClientSDK_JsonVariation(g_pLDClient, flagName.c_str(), defaultValue);
        const char* evaluationString = LDValue_GetString(resultValue);
        flagValue = JSONNode(evaluationString);
        LDValue_Free(resultValue);
        LDValue_Free(defaultValue);`

Since `LDJSONDeserialize` and `LDJSONSerialize` does not have replacement so i used `LDValue_NewString` and `LDValue_GetString` but this does give the same result. Do you have idea what would be the replacement for `LDJSONDeserialize` and `LDJSONSerialize`?

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda , you are correct there is no replacement yet for serializing/deserializing `LDValue` to JSON in C binding, but it is available in C++. 

We could add it, if you require it.

Let me address two issues you bring up.

**Issue 1: incorrect `defaultValue`**

I would like to point out in your example, you are using a JSON array (`value = "[]";`) with `LDValue_NewString`. Instead, you should be using `LDValue_ArrayBuilder` ([reference](https://launchdarkly.github.io/cpp-sdks/libs/client-sdk/docs/html/array__builder_8h.html)).

Example:
```c
#include <launchdarkly/bindings/c/array_builder.h>

// In your function:
LDArrayBuilder array_builder = LDArrayBuilder_New();
LDValue empty_array = LDArrayBuilder_Build(array_builder);

// There is no need to free the LDArrayBuilder if you have called Build, it will be done automatically.
```
Now if you pass `empty_array` into `LDClientSDK_JsonVariation` as the `defaultValue`, it should be returned properly as an empty array. 

**Issue 2: incorrect `resultValue`**

In your example, calling `LDValue_GetString` will only return the correct result if the evaluated result is actually a string. 

Depending on your requirements, you can solve this with existing SDK methods, or we may need `LDJSONSerialize` to be implemented.

For example, if you know the result is always going to be an array, you could use `LDValue_ArrayIter` ([reference](https://launchdarkly.github.io/cpp-sdks/libs/client-sdk/docs/html/value_8h.html#ab8e48a1a361b9a1b3700972e48548dd8)):
```c
LDValue_ArrayIter iter = LDValue_ArrayIter_New(resultValue);
while (!LDValue_ArrayIter_End(iter)) {
       // Please note, you should treat value_ref as const*. It is not copied, it is still owned by the parent resultValue.
       LDValue value_ref = LDValue_ArrayIter_Value(iter);
       // You can do something with the value here.
       handle(value_ref);
       // Advance the iterator.
       LDValue_ArrayIter_Next(iter);
    }
LDValue_ArrayIter_Free(iter);
```

You can do similar with `LDValue_ObjectIter` ([reference](https://launchdarkly.github.io/cpp-sdks/libs/client-sdk/docs/html/value_8h.html#a103e0d5cc1b178bcef3330da7b45ef5d)) if you know the value is a JSON object. You can always determine the type of a JSON value with `LDValue_Type` ([reference](https://launchdarkly.github.io/cpp-sdks/libs/client-sdk/docs/html/value_8h.html#a5d9df547e0c7bd911fd8b0f56048c73a)).

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda , I have filed a new issue with response here: https://github.com/launchdarkly/cpp-sdks/issues/416

Please respond in the new issue. I will close this one, since `LDConfigSetSSLCertificateAuthority` and `LDConfigSetVerifyPeer` are now implemented.
