### ISSUE TITLE
"LDConfigSetProxyURI" not available in 3.0

### ISSUE THREAD

**Issue by ngangomsamananda** [launchdarkly/cpp-sdks#394]
**Is your feature request related to a problem? Please describe.**
 I see in https://docs.launchdarkly.com/sdk/features/web-proxy mentioned "LDConfigSetProxyURI" is not availble in 3.0 yet. We need the replacement of `LDConfigSetProxyURI` in our application. I don't see any ticket on this. So, I have created this ticket to track on the issue.

When can we expect this feature? It will be nice if you could provide all the API's which are in v2.x. Upgrading client sdk to v3.x is delay due to unavailable of equivalent API's.
  
  **Describe the solution you'd like**
  A replacement for` LDConfigSetProxyURI` in v3.x.
  LDConfigSetProxyURI : Set the proxy server used for connecting to LaunchDarkly.
  
  **Describe alternatives you've considered**
  
  **Additional context**

**Comment by cwaldren-ld** [comment]
Hi @ngangomsamananda, are you using an HTTP/HTTPS proxy or SOCKS?

If you are using HTTP/HTTPS, you should be able to use this workaround:

```c
LDClientConfigBuilder ConfigBuilder = LDClientConfigBuilder_New(mobile_key);

LDClientConfigBuilder_ServiceEndpoints_RelayProxyBaseURL(ConfigBuilder, "https://your-proxy-url:your-port");
```

This is intended for using Relay Proxy, but it should also work for setting a general proxy URI. 

At the moment, the SDK does not support SOCKS protocol. Please let me know if that is what you require.

**Comment by ngangomsamananda** [comment]
@cwaldren-ld Yes, we are using the HTTPS proxy. I will use the workaround which you have provided. Thank you.
