### ISSUE TITLE
Could not find a package configuration file provided by "boost_json"

### ISSUE THREAD

**Issue by frankgreco** [launchdarkly/cpp-sdks#397]
I can't seem to get past this error on Debian 👇🏼 
```
3.780 CMake Error at /usr/lib/aarch64-linux-gnu/cmake/Boost-1.81.0/BoostConfig.cmake:141 (find_package):
3.780   Could not find a package configuration file provided by "boost_json"
3.780   (requested version 1.81.0) with any of the following names:
3.780
3.780     boost_jsonConfig.cmake
3.780     boost_json-config.cmake
3.780
3.780   Add the installation prefix of "boost_json" to CMAKE_PREFIX_PATH or set
3.780   "boost_json_DIR" to a directory containing one of the above files.  If
3.780   "boost_json" provides a separate development package or SDK, be sure it has
3.780   been installed.
3.780 Call Stack (most recent call first):
3.780   /usr/lib/aarch64-linux-gnu/cmake/Boost-1.81.0/BoostConfig.cmake:262 (boost_find_component)
3.780   /usr/share/cmake-3.25/Modules/FindBoost.cmake:594 (find_package)
3.780   CMakeLists.txt:133 (find_package)
3.780
3.780
3.780 -- Configuring incomplete, errors occurred!
```

I'm copying commands out of the example Dockerfile (for openresty) and it fails on this command 👇🏼 
```
RUN git clone --branch launchdarkly-cpp-server-v3.3.3 https://github.com/launchdarkly/cpp-sdks.git && \
    cd cpp-sdks && \
    mkdir build-dynamic && \
    cd build-dynamic && \
    cmake -GNinja \
        -DLD_BUILD_EXAMPLES=OFF \
        -DBUILD_TESTING=OFF \
        -DLD_BUILD_SHARED_LIBS=ON \
        -DLD_DYNAMIC_LINK_OPENSSL=ON .. && \
    cmake --build . --target launchdarkly-cpp-server && \
    cmake --install . --prefix=../../cpp-sdk-libs
```

**Comment by cwaldren-ld** [comment]
@frankgreco would you mind sharing how you fixed it in case others encounter it?

**Comment by frankgreco** [comment]
Unfortunately, Debian doesn't have the right version of boost by default so I used Trixie. I gave Debian an honest try by trying to install all of the right packages but gave up when I needed to build the boost url dependency from source.

TBH, if you're going to rely on versions of boost that aren't even in the latest stable versions of OS's like Debian, I'd strongly recommend providing detailed documentation on how to unblock.

**Comment by frankgreco** [comment]
actually @cwaldren-ld I need to use bookworm. could you provide a minimal debian example (not using trixie since it's not stable yet).

**Comment by frankgreco** [comment]
i'm okay with using the latest bookworm as long as it's possible. i've tried for two days to get it working but to no avail so any example would be nice

**Comment by cwaldren-ld** [comment]
Good news, I got it working 👍  

I'll have an example up shortly in the Lua repo using debian:bookworm as the base image.

**Comment by cwaldren-ld** [comment]
It's not merged to main yet, but you can take a look at the Dockerfile in this PR: https://github.com/launchdarkly/lua-server-sdk/pull/101

**Comment by frankgreco** [comment]
sweet! let me try it out!

**Comment by frankgreco** [comment]
@cwaldren-ld great news; that works!!! I'm running into 👇🏼 
```
[LaunchDarkly] backing off in (3) seconds due to Service not found [asio.addrinfo:-8]
```
```
        ld_client = require('launchdarkly_server_sdk').clientInit(
            '<redacted>',
            0,
            {
                offline = false,
                logging = {
                    basic = {
                        level = 'debug'
                    },
                },
                events = {
                    enabled = false,
                },
            }
        )
```
but it could be unrelated

**Comment by cwaldren-ld** [comment]
What operating system are you building the Docker image on?  Exactly what docker command are you using to build the container?

**Comment by frankgreco** [comment]
Actually, I was purging `libboost1.81-all-dev libboost-json1.81-dev libboost-url1.81-dev` after building but it looks like those are required at runtime. after removing the purge, I stopped getting that error.

I'm not getting an SSL error but I'll debug that separately. 

Thanks for all of your help @cwaldren-ld! World class GitHub support 🔥
