### ISSUE TITLE
Access violation issue while creating LDClientSDK client using LDClientSDK_New

### ISSUE THREAD

**Issue by Mayank-Rk-Gupta** [launchdarkly/cpp-sdks#434]
**Is this a support request?**
  No
  
  **Describe the bug**
 I was trying to build [hello-c-client](https://github.com/launchdarkly/cpp-sdks/tree/main/examples/hello-c-client) , in same I am using **LDClientSDK client = LDClientSDK_New(config, context);** to create LD client in my C++ code. I have dynamically link to Client Side SDK and using C interface in my cpp code. However I am getting access violation issue. I beforehand check that config and context are not null.

  
  **To reproduce**

- In Visual Studio 2022 on a Windows computer, I started a new C++ 17 Windows console app.
- I copied the contents of the [hello-c-client](https://github.com/launchdarkly/cpp-sdks/tree/main/examples/hello-c-client) into my new C++ windows console app.
- I downloaded the windows-msvc-x64-dynamic.zip for the launchdarkly-cpp-client v3.6.3 from the [releases page here](https://github.com/launchdarkly/cpp-sdks/releases?page=1&q=%22launchdarkly-cpp-client%22), extracted it, and write cmake to use header and library.
- Use breakpoint to debug through the main function and getting access violation in **LDClientSDK client = LDClientSDK_New(config, context);**
  
  **Expected behavior**
  It should create a Launchdarkly client.
  
  **SDK version**
  3.6.3
  
  **Language version, developer tools**
  C++17 on Visual Studio 2022.
  
  **OS/platform**
  Windows 10
  
  **Additional context**
![image](https://github.com/user-attachments/assets/e7a0f294-5201-4397-8e05-0220fb103b3f)

**Comment by cwaldren-ld** [comment]
Hi @Mayank-Rk-Gupta , there may be some incompatability between the msvc-x64 release we have built on our CI runners, and the version of Visual Studio 2022 you are using locally.

Can you try:
(2) Clicking [Repair](https://stackoverflow.com/questions/78598141/first-stdmutexlock-crashes-in-application-built-with-latest-visual-studio) button in Visual studio
(2) [Update](https://github.com/launchdarkly/cpp-sdks/issues/425#issuecomment-2283494260) Visual Studio to the latest version available
(3) If that doesn't help, try building the project from source using `cmake`.

**Comment by Mayank-Rk-Gupta** [comment]
Hi @cwaldren-ld, sorry for replying late as I was away for some time. I tried with version 17.8 of visual studio it is working so Could you help me with the minimum version of Visual studio required for launchdarkly client initialization and everything to work fine.

**Comment by cwaldren-ld** [comment]
Hi @Mayank-Rk-Gupta , to be clear, are you saying `17.8` **works**?

If it works for you, you should continue using it. Or do you need to use an older version?

**Comment by Mayank-Rk-Gupta** [comment]
Thanks for the information. Yes In our project people are still using some older version of Visual Studio therefore in order to make sure that laucnhdarkly is wokring fine for everyone we need to have an idea which minimum version is exactly require.

**Comment by cwaldren-ld** [comment]
Hi @Mayank-Rk-Gupta , I think that the underlying issue that caused the incompatibility was this, which affected many people: https://github.com/actions/runner-images/issues/10004#issuecomment-2156109231.

I do not fully understand the issue, but I think the main outcome was that the Github Runner images were updated with a fix. 

Therefore what I would recommend is this:

Make sure your developers are using the latest release of the LaunchDarkly Client-side SDK (3.6.4), because the latest releases are built with newer Github runner images that should have the issue resolved. 

I also recommend using the latest VS version, but understand if this isn't possible. 

If they encounter any similar mutex crash, please update this thread.

**Comment by cwaldren-ld** [comment]
Hi @Mayank-Rk-Gupta , is this issue resolved?

**Comment by Mayank-Rk-Gupta** [comment]
Yes, It has been resolved. Thanks for your suggestion.
