### ISSUE TITLE
Client-side SDK Persistence configuration is not working for c-binding

### ISSUE THREAD

**Issue by TouHouPolice** [launchdarkly/cpp-sdks#457]
**Is this a support request?**
  Yes
  
  **Describe the bug**
  After studying your SDK API Docs for c-binding, I understand that `LDPersistence` is the official way of writing and reading from a local cache. My configuration returns no error, but none of my functions are actually called, and no persistent cache is generated of course:
```
    LDClientConfigBuilder builder = LDClientConfigBuilder_New(SDKKey);
    //Other configurations
    //..........
    //Local cache configuration
    if(true)
    {
        LDPersistence persistenceImpl = {};
        persistenceImpl.Set = Persistence::Set; //my own name space and definition
        persistenceImpl.Remove = Persistence::Remove;
        persistenceImpl.Read = Persistence::Read;
        persistenceImpl.FreeRead = Persistence::FreeRead;
        persistenceImpl.UserData = &userData;
        LDPersistence_Init(&persistenceImpl);

        LDPersistenceCustomBuilder persistenceBuilder = LDPersistenceCustomBuilder_New();
        LDPersistenceCustomBuilder_Implementation(persistenceBuilder, persistenceImpl);
        LDClientConfigBuilder_Persistence_Custom(builder, persistenceBuilder);
    }

    LDClientConfig config;
    LDStatus status = LDClientConfigBuilder_Build(builder, &config);
    //....
    LDContextBuilder contextBuilder = LDContextBuilder_New();
    //building context ...
    LDContext context = LDContextBuilder_Build(contextBuilder);
    LDClientSDK client = LDClientSDK_New(config, context);
    bool initialized_successfully;
    if (LDClientSDK_Start(client, kMaxWait, &initialized_successfully)) 
    {
         if (initialized_successfully) // then evaluating some flags
    }
```
  
  **To reproduce**
Initialise a client with the above code, the implementation details are not the issue as they are never even called, any placeholder should be fine.
  
  **Expected behavior**
I expect the functions I have hooked to be invoked upon client initialisation.
  
  **Logs**
I don't see logs related to persistence which should happen before `Client initialization succeeded` if any.
  ```
[LaunchDarkly] event-processor: scheduling flush in 5000ms
[LaunchDarkly] sse-client: connected
[LaunchDarkly] sse-client: read (5) bytes in (0) sec
[LaunchDarkly] sse-client: read (186) bytes in (0) sec
[LaunchDarkly] sse-client: read (512) bytes in (0) sec
[LaunchDarkly] sse-client: read (512) bytes in (0) sec
[LaunchDarkly] sse-client: read (512) bytes in (0) sec
[LaunchDarkly] sse-client: read (512) bytes in (0) sec
[LaunchDarkly] sse-client: read (512) bytes in (0) sec
[LaunchDarkly] sse-client: read (512) bytes in (0) sec
[LaunchDarkly] sse-client: read (511) bytes in (0) sec
[LaunchDarkly] sse-client: read (8) bytes in (0) sec
[LaunchDarkly] sse-client: read (506) bytes in (0) sec
[LaunchDarkly] sse-client: read (514) bytes in (0) sec
[LaunchDarkly] sse-client: read (514) bytes in (0) sec
[LaunchDarkly] sse-client: read (514) bytes in (0) sec
[LaunchDarkly] sse-client: read (514) bytes in (0) sec
[LaunchDarkly] sse-client: read (514) bytes in (0) sec
[LaunchDarkly] sse-client: read (514) bytes in (0) sec
[LaunchDarkly] sse-client: read (514) bytes in (0) sec
[LaunchDarkly] sse-client: read (514) bytes in (0) sec
[LaunchDarkly] sse-client: read (514) bytes in (0) sec
Client initialization succeeded.
  ```
  
  **SDK version**
  cpp-client 3.5.0
  
  **Language version, developer tools**
  C++17, Apple clang version 15.0.0 
  
  **OS/platform**
  Apple M3 Pro, Sonoma 14.3
  
  **Additional context**
  N/A

**Comment by cwaldren-ld** [comment]
Hi @TouHouPolice , I will take a look at this. Thank you for the detailed report, it really helps!

_Filed internally as SDK-771._

**Comment by cwaldren-ld** [comment]
Hi @TouHouPolice , I want to apologize as I think our documentation wasn't clear. 

The function `LDPersistence_Init` is meant to be used to initialize the `LDPersistence` struct **before** you set any of the function pointers. 

The purpose is to ensure the struct doesn't contain garbage/uninitialized values.

```c
        LDPersistence persistenceImpl = {};
        persistenceImpl.Set = Persistence::Set; //my own name space and definition
        persistenceImpl.Remove = Persistence::Remove;
        persistenceImpl.Read = Persistence::Read;
        persistenceImpl.FreeRead = Persistence::FreeRead;
        persistenceImpl.UserData = &userData;

        LDPersistence_Init(&persistenceImpl); <-- this line is setting all of the function pointers to default implementations, and setting UserData to NULL. 
```

Can you try this instead?
```c
        LDPersistence persistenceImpl = {};
        LDPersistence_Init(&persistenceImpl);

        persistenceImpl.Set = Persistence::Set; //my own name space and definition
        persistenceImpl.Remove = Persistence::Remove;
        persistenceImpl.Read = Persistence::Read;
        persistenceImpl.FreeRead = Persistence::FreeRead;
        persistenceImpl.UserData = &userData;
```

**Comment by TouHouPolice** [comment]
Hi @cwaldren-ld, I've already tried `LDPersistence_Init` before setting the values, nothing is happening.

`    {
        LDPersistence persistenceImpl;
        LDPersistence_Init(&persistenceImpl);

        persistenceImpl.Set = Persistence::Set;
        persistenceImpl.Remove = Persistence::Remove;
        persistenceImpl.Read = Persistence::Read;
        persistenceImpl.FreeRead = Persistence::FreeRead;
        persistenceImpl.UserData = &userData;
        

        LDPersistenceCustomBuilder persistenceBuilder = LDPersistenceCustomBuilder_New();
        LDPersistenceCustomBuilder_Implementation(persistenceBuilder, persistenceImpl);
        LDClientConfigBuilder_Persistence_Custom(builder, persistenceBuilder);
    }`

**Comment by cwaldren-ld** [comment]
Hi @TouHouPolice , I copied your code into our "hello c client" example, with some custom persistence functions. When I run it, I see the functions being called:

```
ReadFn called
FreeFn called
[LaunchDarkly] event-processor: scheduling flush in 30000ms
[LaunchDarkly] sse-client: connected

<more sse client logs>
ReadFn called
FreeFn called
SetFn called
SetFn called
*** SDK successfully initialized!

<other log messages omitted>
```

I have created a branch here: https://github.com/launchdarkly/cpp-sdks/blob/cw/test-client-persistence/examples/hello-c-client/main.c#L63

You can test it by building the repo from source. Then running it:
```bash
LD_MOBILE_KEY=your-key ./build/examples/hello-c-client/hello-c-client
```

Can you add `printf` logs to your custom functions, to double check if they are being invoked?

The SDK itself won't log messages related to calling those functions.

**Comment by TouHouPolice** [comment]
I have found the issue, initially it was because I called `LDPersistence_Init ` at the end as mentioned above, and later when I repositioned the call, some code was duplicated incorreclty resulting the issue I experienced.
In short, it was because of my mistake. Thanks @cwaldren-ld for helping.
Closing it now.

**Comment by cwaldren-ld** [comment]
Hi @TouHouPolice , glad you were able to resolve it. Our docs are now updated so it should be clearer for the next person, so thanks for bringing it up!
