### ISSUE TITLE
Security Vulnerability in launchdarkly-cpp-client.dll due to OpenSSL 3.1.1

### ISSUE THREAD

**Issue by Mayank-Rk-Gupta** [launchdarkly/cpp-sdks#461]
**Is this a support request?**
  No
  
  
  **Describe the bug**
We are currently facing a security vulnerability issue in the launchdarkly-cpp-client.dll that is linked to the version of OpenSSL included in the client, which is 3.1.1. This version of OpenSSL has known security vulnerabilities that could pose risks to our application’s security.

SDK Version: 3.6.4
OpenSSL Version: 3.1.1

Potential exposure to security risks, which could affect the confidentiality, integrity, and availability of our system.

  
  **Expected behavior**
  We would like to request a version of the launchdarkly-cpp-client.dll built with a more secure version of OpenSSL.
  
  
  **SDK version**
  3.6.4
  

  
  **OS/platform**
 Windows
  
  **Additional context**

**Comment by cwaldren-ld** [comment]
Hi @Mayank-Rk-Gupta , thank you for bringing this to my attention.

You can dynamically link against OpenSSL using CMake variable `LD_DYNAMIC_LINK_OPENSSL=On`. That way, you are able to upgrade the OpenSSL library independently.

In the mean time, I will investigate upgrading the statically-linked version that is used in Windows builds.

_Filed internally as SDK-810._

**Comment by cwaldren-ld** [comment]
Hi @Mayank-Rk-Gupta , good news: I was able to build the SDK using OpenSSL 3.4.0 and Boost 1.81 on Windows. I will work on preparing a release for it.

**Comment by cwaldren-ld** [comment]
Hi @Mayank-Rk-Gupta , I have prepared a release for you: https://github.com/launchdarkly/cpp-sdks/releases/tag/launchdarkly-cpp-client-v3.7.1-openssl3.4

Please note, this is a re-release of the existing 3.7.1 client but using OpenSSL 3.4 which was released two days ago. Future SDK releases on windows will be built with this version as well.

**Comment by cwaldren-ld** [comment]
Hi @Mayank-Rk-Gupta , I'm going to close this now. Feel free to file a new issue if you need more support.
